name: kos-v1
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${KOS_PGADMIN_CONTAINER_NAME}
    ports:
    - 8086:80
    environment:
    - PGADMIN_CONTAINER_NAME=${KOS_PGADMIN_CONTAINER_NAME}
    - PGADMIN_EMAIL=admin@kos.local
    - PGADMIN_ENABLE=true
    - PGADMIN_EXTERNAL_PORT=8086
    - PGADMIN_HOST=localhost
    - PGADMIN_IMAGE=dpage/pgadmin4:latest
    - PGADMIN_INTERNAL_PORT=80
    - PGADMIN_PASSWORD=kos-30437
    - PGADMIN_PROFILE=admin
    - PGADMIN_USER=kos-admin
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    - PGADMIN_DEFAULT_EMAIL=admin@kos.local
    - PGADMIN_DEFAULT_PASSWORD=kos-30437
    volumes:
    - kos-pgadmin-data:/data
    networks:
    - kos-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:80/misc/ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  redis_commander:
    image: rediscommander/redis-commander:latest
    container_name: ${KOS_REDIS_COMMANDER_CONTAINER_NAME}
    ports:
    - 8085:8081
    environment:
    - REDIS_COMMANDER_CONTAINER_NAME=${KOS_REDIS_COMMANDER_CONTAINER_NAME}
    - REDIS_COMMANDER_ENABLE=true
    - REDIS_COMMANDER_EXTERNAL_PORT=8085
    - REDIS_COMMANDER_HOST=localhost
    - REDIS_COMMANDER_IMAGE=rediscommander/redis-commander:latest
    - REDIS_COMMANDER_INTERNAL_PORT=8081
    - REDIS_COMMANDER_PASSWORD=kos-30437
    - REDIS_COMMANDER_PROFILE=admin
    - REDIS_COMMANDER_REDIS_HOSTS=local:redis:6379:0:kos-30437
    - REDIS_COMMANDER_USER=kos-admin
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    - REDIS_COMMANDER_USER=kos-admin
    - REDIS_COMMANDER_PASSWORD=kos-30437
    volumes:
    - kos-redis_commander-data:/data
    networks:
    - kos-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  mongo_express:
    image: mongo-express:latest
    container_name: ${KOS_MONGO_EXPRESS_CONTAINER_NAME}
    ports:
    - 8087:8081
    environment:
    - MONGO_EXPRESS_CONTAINER_NAME=${KOS_MONGO_EXPRESS_CONTAINER_NAME}
    - MONGO_EXPRESS_ENABLE=true
    - MONGO_EXPRESS_EXTERNAL_PORT=8087
    - MONGO_EXPRESS_HOST=localhost
    - MONGO_EXPRESS_IMAGE=mongo-express:latest
    - MONGO_EXPRESS_INTERNAL_PORT=8081
    - MONGO_EXPRESS_PASSWORD=kos-30437
    - MONGO_EXPRESS_PROFILE=admin
    - MONGO_EXPRESS_USER=kos-admin
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    - MONGO_EXPRESS_USER=kos-admin
    - MONGO_EXPRESS_PASSWORD=kos-30437
    volumes:
    - kos-mongo_express-data:/data
    networks:
    - kos-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:8081 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  admin_panel:
    image: portainer/portainer-ce:latest
    container_name: kos-admin-panel
    ports:
    - 9003:9003
    environment:
    - ADMIN_PANEL_CONTAINER_NAME=kos-admin-panel
    - ADMIN_PANEL_ENABLE=true
    - ADMIN_PANEL_EXTERNAL_PORT=9003
    - ADMIN_PANEL_IMAGE=portainer/portainer-ce:latest
    - ADMIN_PANEL_INTERNAL_PORT=9003
    - ADMIN_PANEL_PROFILE=admin
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    volumes:
    - kos-admin_panel-data:/data
    networks:
    - kos-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:9003/api/status || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
  registry:
    image: registry:2
    container_name: ${KOS_REGISTRY_CONTAINER_NAME}
    ports:
    - 5000:5000
    environment:
    - REGISTRY_CONTAINER_NAME=${KOS_REGISTRY_CONTAINER_NAME}
    - REGISTRY_ENABLE=true
    - REGISTRY_EXTERNAL_PORT=5000
    - REGISTRY_HOST=localhost
    - REGISTRY_IMAGE=registry:2
    - REGISTRY_INTERNAL_PORT=5000
    - REGISTRY_PROFILE=admin
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    volumes:
    - kos-registry-data:/data
    networks:
    - kos-network
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - curl -f http://localhost:5000/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
networks:
  kos-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
volumes:
  kos-mongo_express-data:
    driver: local
  kos-registry-data:
    driver: local
  kos-admin_panel-data:
    driver: local
  kos-redis_commander-data:
    driver: local
  kos-pgadmin-data:
    driver: local
