name: kos-v1
services:
  nginx:
    image: nginx:alpine
    container_name: kos-nginx
    ports:
    - 80:80
    environment:
    - NGINX_CATEGORY=core
    - NGINX_COMPOSE_GROUP=core
    - NGINX_CONFIG_VOLUME=kos-nginx:/config
    - NGINX_CONTAINER_NAME=kos-nginx
    - NGINX_DEPENDS_ON=frontend,api
    - NGINX_ENABLE=true
    - NGINX_EXTERNAL_PORT=80
    - NGINX_HEALTH_CHECK_COMMAND=curl -f http://kos-nginx:80 || exit 1
    - NGINX_HEALTH_CHECK_INTERVAL=30s
    - NGINX_HEALTH_CHECK_RETRIES=3
    - NGINX_HEALTH_CHECK_TIMEOUT=10s
    - NGINX_IMAGE=nginx:alpine
    - NGINX_INTERNAL_PORT=80
    - NGINX_LOGS_VOLUME=kos-nginx:/logs
    - NGINX_NETWORK=kos-network
    - NGINX_PROFILE=core
    - NGINX_RESTART_POLICY=unless-stopped
    - NGINX_SSL_EXTERNAL_PORT=443
    - NGINX_SSL_INTERNAL_PORT=443
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    volumes:
    - type: volume
      source: kos-nginx
      target: /config
      volume: {}
    - type: volume
      source: kos-nginx
      target: /logs
      volume: {}
    networks:
    - kos-network
    restart: unless-stopped
networks:
  kos-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
volumes:
  kos-nginx:
    driver: local
