name: kos-v1
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: kos-n8n
    ports:
    - 5678:5678
    environment:
    - N8N_BASIC_AUTH_PASSWORD=kos30437
    - N8N_BASIC_AUTH_USER=kosadmin
    - N8N_CATEGORY=workflow
    - N8N_COMPOSE_GROUP=workflow
    - N8N_CONTAINER_NAME=kos-n8n
    - N8N_DB_POSTGRESDB_DATABASE=n8n
    - N8N_DB_POSTGRESDB_HOST=kos-postgres
    - N8N_DB_POSTGRESDB_PASSWORD=kos30437
    - N8N_DB_POSTGRESDB_PORT=5432
    - N8N_DB_POSTGRESDB_USER=kosadmin
    - N8N_DB_TYPE=postgresdb
    - N8N_DEPENDS_ON=postgres
    - N8N_ENABLE=true
    - N8N_EXTERNAL_PORT=5678
    - N8N_HEALTH_CHECK_COMMAND=curl -f http://kos-n8n:5678 || exit 1
    - N8N_HEALTH_CHECK_INTERVAL=30s
    - N8N_HEALTH_CHECK_RETRIES=3
    - N8N_HEALTH_CHECK_TIMEOUT=10s
    - N8N_IMAGE=n8nio/n8n:latest
    - N8N_INTERNAL_PORT=5678
    - N8N_NETWORK=kos-network
    - N8N_PROFILE=workflow
    - N8N_RESTART_POLICY=unless-stopped
    - N8N_WEBHOOK_URL=http://kos-n8n:5678/
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    networks:
    - kos-network
    restart: unless-stopped
  nextcloud:
    image: nextcloud:25.0.0
    container_name: kos-nextcloud
    ports:
    - 8083:80
    environment:
    - NEXTCLOUD_ADMIN_PASSWORD=kos30437
    - NEXTCLOUD_ADMIN_USER=kosadmin
    - NEXTCLOUD_CATEGORY=workflow
    - NEXTCLOUD_COMPOSE_GROUP=workflow
    - NEXTCLOUD_CONTAINER_NAME=kos-nextcloud
    - NEXTCLOUD_DB_HOST=kos-postgres
    - NEXTCLOUD_DB_NAME=nextcloud
    - NEXTCLOUD_DB_PASSWORD=kos30437
    - NEXTCLOUD_DB_PORT=5432
    - NEXTCLOUD_DB_TYPE=pgsql
    - NEXTCLOUD_DEPENDS_ON=postgres
    - NEXTCLOUD_ENABLE=true
    - NEXTCLOUD_EXTERNAL_PORT=8083
    - NEXTCLOUD_HEALTH_CHECK_COMMAND=curl -f http://kos-nextcloud:80/status.php ||
      exit 1
    - NEXTCLOUD_HEALTH_CHECK_INTERVAL=30s
    - NEXTCLOUD_HEALTH_CHECK_RETRIES=3
    - NEXTCLOUD_HEALTH_CHECK_TIMEOUT=10s
    - NEXTCLOUD_IMAGE=nextcloud:25.0.0
    - NEXTCLOUD_INTERNAL_PORT=80
    - NEXTCLOUD_NETWORK=kos-network
    - NEXTCLOUD_PROFILE=core
    - NEXTCLOUD_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    networks:
    - kos-network
    restart: unless-stopped
  penpot:
    image: penpotapp/frontend:latest
    container_name: kos-penpot
    ports:
    - 9002:9002
    environment:
    - PENPOT_ADMIN_PASSWORD=kos30437
    - PENPOT_ADMIN_USER=kosadmin
    - PENPOT_CATEGORY=workflow
    - PENPOT_COMPOSE_GROUP=workflow
    - PENPOT_CONTAINER_NAME=kos-penpot
    - PENPOT_DATABASE_URI=postgresql://kosadmin:kos30437@kos-postgres:5432/penpot
    - PENPOT_DEPENDS_ON=postgres,redis
    - PENPOT_ENABLE=true
    - PENPOT_EXTERNAL_PORT=9002
    - PENPOT_HEALTH_CHECK_COMMAND=curl -f http://kos-penpot:9002 || exit 1
    - PENPOT_HEALTH_CHECK_INTERVAL=30s
    - PENPOT_HEALTH_CHECK_RETRIES=3
    - PENPOT_HEALTH_CHECK_TIMEOUT=10s
    - PENPOT_IMAGE=penpotapp/frontend:latest
    - PENPOT_INTERNAL_PORT=9002
    - PENPOT_NETWORK=kos-network
    - PENPOT_PROFILE=workflow
    - PENPOT_REDIS_URI=redis://kos-redis:6379/0
    - PENPOT_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    networks:
    - kos-network
    restart: unless-stopped
networks:
  kos-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
volumes: {}
