name: kos-v1
services:
  automatic1111:
    image: ashleykza/stable-diffusion-webui:latest
    container_name: kos-automatic1111
    ports:
    - 7860:7860
    environment:
    - AUTOMATIC1111_CATEGORY=ai
    - AUTOMATIC1111_COMMANDLINE_ARGS=--listen --port 7860 --enable-insecure-extension-access
    - AUTOMATIC1111_COMPOSE_GROUP=ai
    - AUTOMATIC1111_CONTAINER_NAME=kos-automatic1111
    - AUTOMATIC1111_DEPENDS_ON=
    - AUTOMATIC1111_ENABLE=true
    - AUTOMATIC1111_EXTERNAL_PORT=7860
    - AUTOMATIC1111_HEALTH_CHECK_COMMAND=curl -f http://kos-automatic1111:7860 ||
      exit 1
    - AUTOMATIC1111_HEALTH_CHECK_INTERVAL=30s
    - AUTOMATIC1111_HEALTH_CHECK_RETRIES=3
    - AUTOMATIC1111_HEALTH_CHECK_TIMEOUT=10s
    - AUTOMATIC1111_IMAGE=ashleykza/stable-diffusion-webui:latest
    - AUTOMATIC1111_INTERNAL_PORT=7860
    - AUTOMATIC1111_NETWORK=kos-network
    - AUTOMATIC1111_PROFILE=core
    - AUTOMATIC1111_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    networks:
    - kos-network
    restart: unless-stopped
  comfyui:
    image: zhangp365/comfyui:latest
    container_name: kos-comfyui
    ports:
    - 8188:8188
    environment:
    - COMFYUI_CATEGORY=ai
    - COMFYUI_COMPOSE_GROUP=ai
    - COMFYUI_CONTAINER_NAME=kos-comfyui
    - COMFYUI_DEPENDS_ON=
    - COMFYUI_ENABLE=true
    - COMFYUI_EXTERNAL_PORT=8188
    - COMFYUI_HEALTH_CHECK_COMMAND=curl -f http://kos-comfyui:8188 || exit 1
    - COMFYUI_HEALTH_CHECK_INTERVAL=30s
    - COMFYUI_HEALTH_CHECK_RETRIES=3
    - COMFYUI_HEALTH_CHECK_TIMEOUT=10s
    - COMFYUI_IMAGE=zhangp365/comfyui:latest
    - COMFYUI_INTERNAL_PORT=8188
    - COMFYUI_NETWORK=kos-network
    - COMFYUI_PROFILE=core
    - COMFYUI_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    networks:
    - kos-network
    restart: unless-stopped
  invokeai:
    image: ghcr.io/invoke-ai/invokeai:latest
    container_name: kos-invokeai
    ports:
    - 8189:8189
    environment:
    - INVOKEAI_CATEGORY=ai
    - INVOKEAI_COMPOSE_GROUP=ai
    - INVOKEAI_CONTAINER_NAME=kos-invokeai
    - INVOKEAI_DEPENDS_ON=
    - INVOKEAI_ENABLE=true
    - INVOKEAI_EXTERNAL_PORT=8189
    - INVOKEAI_HEALTH_CHECK_COMMAND=curl -f http://kos-invokeai:8189 || exit 1
    - INVOKEAI_HEALTH_CHECK_INTERVAL=30s
    - INVOKEAI_HEALTH_CHECK_RETRIES=3
    - INVOKEAI_HEALTH_CHECK_TIMEOUT=10s
    - INVOKEAI_IMAGE=ghcr.io/invoke-ai/invokeai:latest
    - INVOKEAI_INTERNAL_PORT=8189
    - INVOKEAI_NETWORK=kos-network
    - INVOKEAI_PROFILE=core
    - INVOKEAI_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    networks:
    - kos-network
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: kos-ollama
    ports:
    - 11434:11434
    environment:
    - OLLAMA_CATEGORY=ai
    - OLLAMA_COMPOSE_GROUP=ai
    - OLLAMA_CONTAINER_NAME=kos-ollama
    - OLLAMA_DEPENDS_ON=
    - OLLAMA_ENABLE=true
    - OLLAMA_EXTERNAL_PORT=11434
    - OLLAMA_HEALTH_CHECK_COMMAND=curl -f http://kos-ollama:11434/api/tags || exit
      1
    - OLLAMA_HEALTH_CHECK_INTERVAL=30s
    - OLLAMA_HEALTH_CHECK_RETRIES=3
    - OLLAMA_HEALTH_CHECK_TIMEOUT=10s
    - OLLAMA_IMAGE=ollama/ollama:latest
    - OLLAMA_INTERNAL_PORT=11434
    - OLLAMA_NETWORK=kos-network
    - OLLAMA_PROFILE=core
    - OLLAMA_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    networks:
    - kos-network
    restart: unless-stopped
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: kos-openwebui
    ports:
    - 3001:8080
    environment:
    - OPENWEBUI_ADMIN_PASSWORD=kos-30437
    - OPENWEBUI_ADMIN_USER=kos-admin
    - OPENWEBUI_CATEGORY=ai
    - OPENWEBUI_COMPOSE_GROUP=ai
    - OPENWEBUI_CONTAINER_NAME=kos-openwebui
    - OPENWEBUI_DEPENDS_ON=ollama
    - OPENWEBUI_ENABLE=true
    - OPENWEBUI_EXTERNAL_PORT=3001
    - OPENWEBUI_HEALTH_CHECK_COMMAND=curl -f http://kos-openwebui:8080 || exit 1
    - OPENWEBUI_HEALTH_CHECK_INTERVAL=30s
    - OPENWEBUI_HEALTH_CHECK_RETRIES=3
    - OPENWEBUI_HEALTH_CHECK_TIMEOUT=10s
    - OPENWEBUI_IMAGE=ghcr.io/open-webui/open-webui:main
    - OPENWEBUI_INTERNAL_PORT=8080
    - OPENWEBUI_NETWORK=kos-network
    - OPENWEBUI_PROFILE=core
    - OPENWEBUI_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kos-admin
    - ADMIN_PASSWORD=kos-30437
    networks:
    - kos-network
    restart: unless-stopped
    depends_on:
    - ollama
networks:
  kos-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
volumes: {}
