name: kos-v1
services:
  automatic1111:
    image: ashleykza/stable-diffusion-webui:latest
    container_name: kos-automatic1111
    ports:
    - 7860:7860
    environment:
    - AUTOMATIC1111_CATEGORY=ai
    - AUTOMATIC1111_COMMANDLINE_ARGS=--listen --port 7860 --ckpt-dir "/models/checkpoints"
      --vae-dir "/models/vae" --embeddings-dir "/models/embeddings" --hypernetwork-dir
      "/models/hypernetworks" --lora-dir "/models/loras"
    - AUTOMATIC1111_COMPOSE_GROUP=ai
    - AUTOMATIC1111_CONFIG_VOLUME=kos-automatic1111:/config
    - AUTOMATIC1111_CONTAINER_NAME=kos-automatic1111
    - AUTOMATIC1111_DEPENDS_ON=
    - AUTOMATIC1111_ENABLE=true
    - AUTOMATIC1111_EXTENSIONS_VOLUME=kos-models-data:/extensions
    - AUTOMATIC1111_EXTERNAL_PORT=7860
    - AUTOMATIC1111_HEALTH_CHECK_COMMAND=curl -f http://kos-automatic1111:7860 ||
      exit 1
    - AUTOMATIC1111_HEALTH_CHECK_INTERVAL=30s
    - AUTOMATIC1111_HEALTH_CHECK_RETRIES=3
    - AUTOMATIC1111_HEALTH_CHECK_TIMEOUT=10s
    - AUTOMATIC1111_IMAGE=ashleykza/stable-diffusion-webui:latest
    - AUTOMATIC1111_INTERNAL_PORT=7860
    - AUTOMATIC1111_MODELS_VOLUME=//e/ComfyUI_WPN/ComfyUI/models:/models
    - AUTOMATIC1111_NETWORK=kos-network
    - AUTOMATIC1111_OUTPUTS_VOLUME=kos-models-data:/outputs
    - AUTOMATIC1111_PROFILE=core
    - AUTOMATIC1111_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    volumes:
    - kos-models-data:/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    networks:
    - kos-network
    restart: unless-stopped
  comfyui:
    image: zhangp365/comfyui:latest
    container_name: kos-comfyui
    ports:
    - 8188:8188
    environment:
    - COMFYUI_CATEGORY=ai
    - COMFYUI_COMPOSE_GROUP=ai
    - COMFYUI_CONFIG_VOLUME=kos-comfyui:/config
    - COMFYUI_CONTAINER_NAME=kos-comfyui
    - COMFYUI_CUSTOM_NODES_VOLUME=kos-comfyui:/custom-nodes
    - COMFYUI_DEPENDS_ON=
    - COMFYUI_ENABLE=true
    - COMFYUI_EXTERNAL_PORT=8188
    - COMFYUI_HEALTH_CHECK_COMMAND=curl -f http://kos-comfyui:8188 || exit 1
    - COMFYUI_HEALTH_CHECK_INTERVAL=30s
    - COMFYUI_HEALTH_CHECK_RETRIES=3
    - COMFYUI_HEALTH_CHECK_TIMEOUT=10s
    - COMFYUI_IMAGE=zhangp365/comfyui:latest
    - COMFYUI_INTERNAL_PORT=8188
    - COMFYUI_MODELS_VOLUME=//e/ComfyUI_WPN/ComfyUI/models:/models
    - COMFYUI_NETWORK=kos-network
    - COMFYUI_OUTPUTS_VOLUME=kos-models-data:/outputs
    - COMFYUI_PROFILE=core
    - COMFYUI_RESTART_POLICY=unless-stopped
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    volumes:
    - kos-models-data:/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities:
            - gpu
    networks:
    - kos-network
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: kos-ollama
    ports:
    - 11434:11434
    environment:
    - OLLAMA_CATEGORY=ai
    - OLLAMA_COMPOSE_GROUP=ai
    - OLLAMA_CONTAINER_NAME=kos-ollama
    - OLLAMA_DEPENDS_ON=
    - OLLAMA_ENABLE=true
    - OLLAMA_EXTERNAL_PORT=11434
    - OLLAMA_HEALTH_CHECK_COMMAND=curl -f http://kos-ollama:11434/api/tags || exit
      1
    - OLLAMA_HEALTH_CHECK_INTERVAL=30s
    - OLLAMA_HEALTH_CHECK_RETRIES=3
    - OLLAMA_HEALTH_CHECK_TIMEOUT=10s
    - OLLAMA_IMAGE=ollama/ollama:latest
    - OLLAMA_INTERNAL_PORT=11434
    - OLLAMA_NETWORK=kos-network
    - OLLAMA_PROFILE=core
    - OLLAMA_RESTART_POLICY=unless-stopped
    - OLLAMA_VOLUME=kos-ollama:/data
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    volumes:
    - type: volume
      source: kos-ollama
      target: /data
      volume: {}
    networks:
    - kos-network
    restart: unless-stopped
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: kos-openwebui
    ports:
    - 3001:8080
    environment:
    - OPENWEBUI_ADMIN_PASSWORD=kos30437
    - OPENWEBUI_ADMIN_USER=kosadmin
    - OPENWEBUI_CATEGORY=ai
    - OPENWEBUI_COMPOSE_GROUP=ai
    - OPENWEBUI_CONTAINER_NAME=kos-openwebui
    - OPENWEBUI_DEPENDS_ON=ollama
    - OPENWEBUI_ENABLE=true
    - OPENWEBUI_EXTERNAL_PORT=3001
    - OPENWEBUI_HEALTH_CHECK_COMMAND=curl -f http://kos-openwebui:8080 || exit 1
    - OPENWEBUI_HEALTH_CHECK_INTERVAL=30s
    - OPENWEBUI_HEALTH_CHECK_RETRIES=3
    - OPENWEBUI_HEALTH_CHECK_TIMEOUT=10s
    - OPENWEBUI_IMAGE=ghcr.io/open-webui/open-webui:main
    - OPENWEBUI_INTERNAL_PORT=8080
    - OPENWEBUI_NETWORK=kos-network
    - OPENWEBUI_OLLAMA_API_BASE_URL=http://kos-ollama:11434
    - OPENWEBUI_PROFILE=core
    - OPENWEBUI_RESTART_POLICY=unless-stopped
    - OPENWEBUI_VOLUME=kos-openwebui:/data
    - ADMIN_USER=kosadmin
    - ADMIN_PASSWORD=kos30437
    volumes:
    - type: volume
      source: kos-openwebui
      target: /data
      volume: {}
    networks:
    - kos-network
    restart: unless-stopped
    depends_on:
    - ollama
networks:
  kos-network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
volumes:
  kos-ollama:
    driver: local
  kos-openwebui:
    driver: local
  kos-models-data:
    driver: local
